// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xugrcbcucnosqrmaotjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Z3JjYmN1Y25vc3FybWFvdGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjU2NzksImV4cCI6MjA3NDE0MTY3OX0.j7qMjoNWaWbN52fpJpCTBjUlDMC92G-k_6h5ep-Eax8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});